// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9HyHNpaNx5g96PQZIbFzcm_z958nBV_w',
    appId: '1:260880272383:android:c19e8eefc570297ddaf5ca',
    messagingSenderId: '260880272383',
    projectId: 'fireecommerce-11e32',
    databaseURL: 'https://fireecommerce-11e32-default-rtdb.firebaseio.com',
    storageBucket: 'fireecommerce-11e32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVnFYKXjzHCyn3_hZbW-8Fhj7jUd85RVg',
    appId: '1:260880272383:ios:4075be8f18253612daf5ca',
    messagingSenderId: '260880272383',
    projectId: 'fireecommerce-11e32',
    databaseURL: 'https://fireecommerce-11e32-default-rtdb.firebaseio.com',
    storageBucket: 'fireecommerce-11e32.appspot.com',
    androidClientId: '260880272383-a9elb0b7e3ico9utu7uvldkfurep4mno.apps.googleusercontent.com',
    iosClientId: '260880272383-68qem4qgad25a586l09e2fnmqp1aefuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.intouch',
  );
}
